name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make check
      run: make check

  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git make mingw-w64-ucrt-x86_64-gcc
    - name: build-and-test
      run: |
        make
        make check

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make CC=clang CFLAGS='-O3 -march=native -flto=thin'
    - name: make check
      run: make check
